apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yarapi

resources:
  - deployment.yaml
  - service.yaml
  - virtualservice.yaml

labels:
  - includeSelectors: true
    pairs:
      app: yarapi
